### PR TITLE
Allow TOML 1.0.0 Mixed Type Arrays

### PR DESCRIPTION
**Pull request by sbuttgereit**
This a revision of the original PR (https://github.com/bitwalker/toml-elixir/pull/24) submitted by @jrogov allowing mixed-type arrays.

This version of the PR includes all of the changes in the original and adapts the mixed-type array tests from https://github.com/BurntSushi/toml-test and corrects a test suite issue related to table arrays.

### CODE REVIEW

**Comment by sbuttgereit** [comment]
Just a couple notes.  

I expect that it's not possible for me to update the original PR so I'm opening a new one including the changes from the original; if it is possible, that's more GitHub than I know :-).

On the original PR I commented that I was having trouble getting the "valid" tests to fail when they should  I figured out why that is the case and it looks like a bad type expectation in https://github.com/bitwalker/toml-elixir/blob/master/test/support/assertions.ex:

```elixir
  def assert_deep_equal(a, b) do
    if do_deep_equal(a, b) do
      assert true
    else
      assert a == b
    end
  end
```

This function tests the output `do_deep_equal/2` to either pass or fail the test.  The issue I was observing arises beacause `do_deep_equal/2` can return either a boolean in the simple case or nested lists of booleans.  The lists are returned when the `do_deep_equal/2` function heads which involve comprehensions are used.  The comprehensions return a list of results rather than a simple true/false result depending on if the result of the tests all succeeded or not.  Since the `if` call in `assert_deep_equals/2` is a "truthy" evaluation even a list of false results will end up at `assert true`.  Seems like the comprehension results from `do_deep_equal/2` would need to be flattened/reduced to meet the expectations of `assert_deep_equal/2` if I'm understanding things correctly (and I may not be).

I tried some simple fixes to do that flatten/reduce, but ended up with more than half of the tests failing.  Glossing over those results it looked like it had mostly to do with comparisons of the tomt-test tests which are in a different form than the extended testing.   Anyway, assuming that my assumptions are correct, I'd suggest that I just open up an issue documenting the testing issue and allow that to be handled in a different dedicated PR since it seems out of scope for this one.

**Comment by sbuttgereit** [comment]
One other note/question: the documentation and some comments reference TOML 0.5.0 as being supported but if this PR is merged, that won't be strictly true.  Should those references be updated?

**Comment by sbuttgereit** [comment]
Hi @bitwalker --  

I just wanted to bump this one a bit.  If there's some possibility to take a look at this I'd be thankful.  I'm currently using this PR branch in a project and, insofar as anecdote is worth, it's working well for me.  

If there's not time I completely understand. 

Thanks,
Steve

**Comment by bitwalker** [comment]
@sbuttgereit Sorry for the long delay in getting to this!

>  the documentation and some comments reference TOML 0.5.0 as being supported but if this PR is merged, that won't be strictly true. Should those references be updated?

Yes, we should update those references to 1.0.

> Anyway, assuming that my assumptions are correct, I'd suggest that I just open up an issue documenting the testing issue and allow that to be handled in a different dedicated PR since it seems out of scope for this one.

Could you clarify a bit what the testing issue means? Are the failing tests redundant, in that we have other tests which verify that the library upholds the TOML spec, but some of the legacy tests are failing because of behavior changes? Or do the failing tests have no clear alternative/replacements and imply that there is functionality that may be broken which we'll need to address? Just want to make sure I know what the implications are here of merging this as-is.

**Comment by sbuttgereit** [comment]
Regarding the testing issue.  Some points to be sure we're on the same page:

- The testing issue found and this pull request are only related in that I discovered the problem while working with the tests in the PR.  Otherwise the testing issue isn't related to any of the changes in the PR and I can demonstrate the issue using the master branch.
- My focus will be on the `fixtures/toml-test/valid` tests.  I may have played around with the additional tests, but I just can't recal.

So the basic issue is that a test which should fail, succeeds.  Let's consider test `arrays-hetergeneous`.  Note that these are tested against `master` and not the PR code.

The TOML which is exercised for this test is:

```toml
mixed = [[1, 2], ["a", "b"], [1.1, 2.1]]
```
The test code will then generate a test which compares the result of parsing the TOML against a JSON file which provides a description of the expected output:

```json
{
    "mixed": {
        "type": "array",
        "value": [
            {"type": "array", "value": [
                {"type": "integer", "value": "1"},
                {"type": "integer", "value": "2"}
            ]},
            {"type": "array", "value": [
                {"type": "string", "value": "a"},
                {"type": "string", "value": "b"}
            ]},
            {"type": "array", "value": [
                {"type": "float", "value": "1.1"},
                {"type": "float", "value": "2.1"}
            ]}
        ]
    }
}
```

If the comparison succeeds, we should expect to see a successful test result, which we do.:

```
[CLIP]

  * test arrays-hetergeneous is valid (34.1ms) [L#27] (green)

Finished in 3.0 seconds (0.00s async, 3.0s sync)
126 tests, 0 failures, 125 excluded
``` 

Now if I change the TOML file to be something different while the JSON description remains the same, for example:

```toml
mixed = [[1, 2], ["This", "should", "fail"], ["!"] , [1.1, 2.1]]
```
my understanding is that this should now fail since the values are different and there are extra elements in the top level array. 

But I get the same result as the original TOML:

```
* test arrays-hetergeneous is valid (28.4ms) [L#27] (green)

Finished in 2.8 seconds (0.00s async, 2.8s sync)
126 tests, 0 failures, 125 excluded
```

Same if there are fewer elements or different values.  For example the following will also pass the test when compared with the original JSON:

```toml
mixed = [[4, 5], [1.6, 2.7]]
```

And this gets to the gist of what I think I found with `Assertions.assert_deep_equal/2`.  The `Assertions.do_deep_equal/2`  code called by `assert_deep_equal/2` does the evaluation and the tests for simple TOML examples will evaluate to a simple boolean `true` on success or `false` on failure.  In these more complex array and nested structures, however, what `do_deep_equal/2` returns is a list of `true`/`false` values for each of the elements evaluated and this is where I think things goes wrong:

```elixir
  def assert_deep_equal(a, b) do
    if do_deep_equal(a, b) do
      assert true
    else
      assert a == b
    end
  end
```

The `if` call which evaluates the result of `do_deep_equal/2` will evaluate to `true` even if the return value of `do_deep_equal/2` is a list of all `false` values meaning that each evaluation resulted in failure; this is because a non-empty list is truthy, even one with nothing but `false` elements.  My sense is that there's a reduce step missing, but didn't follow it any further.

**Comment by bitwalker** [comment]
@sbuttgereit Ah I see, indeed that is broken. I'm going to merge this PR then, and push a fix for the testing issue. Would you be willing to give me a hand in fixing any broken tests after that?

**Comment by sbuttgereit** [comment]
> Would you be willing to give me a hand in fixing any broken tests after that?

Sure.  Happy to help.  I'll open the testing remarks as an issue so there's some visibility outside of the PR; let me know if you'd rather not manage it there and I can kill/close the issue I open.

**Comment by sbuttgereit** [comment]
> I'll open the testing remarks as an issue so there's some visibility outside of the PR; let me know if you'd rather not manage it there and I can kill/close the issue I open.

Nevermind... I see that there's an older issue. I'll try running this tomorrow, probably later in the evening.

**Comment by bitwalker** [comment]
@sbuttgereit I've gone ahead and fixed up the tests, so assuming there are no new additional tests needed for 1.0, we should be good!

**Pull request merged**
