### PR TITLE
Remove overprotective array type check

### PR DESCRIPTION
**Pull request by jrogov**
Toml spec clearly says that elements of arrays can have different types
>  Arrays can contain values of the same data types as allowed in key/value pairs. 

Details: https://github.com/toml-lang/toml#user-content-array

This PR removes those checks.

### CODE REVIEW

**Comment by arikai** [comment]
Only now I've noticed a bigger picture. That is, that this library targets version 0.5 of TOML spec.

Then, an actual question is, is there any plan to support 1.0+?

**Comment by bitwalker** [comment]
I'm not opposed to supporting 1.0, though I don't believe much has changed since 0.5. However, since heterogenous arrays are now supported in 1.0, I don't see any problem with supporting that even if we haven't done a full audit for 1.0 changes.

**Comment by sbuttgereit** [comment]
Hi-- @jrogov, @bitwalker

I didn't read the documentation very well and was building a TOML file according to the v1.0 spec and ran into the multi-type array support change being addressed by this PR.  I have a use case where this PR would help me avoid a lot of boiler plate and so have some interest in seeing it land.

I wouldn't mind adding the tests if that's OK?  If I'm reading things correctly, is this really about creating .toml files in the valid test fixtures directory exercising mixed type arrays?

**Comment by bitwalker** [comment]
@sbuttgereit That'd be great! Would love to get this merged, but I haven't had time to work on it myself.

To answer your question though, yes, adding test fixtures and tests that exercise them and verify the results is all that's needed - the goal is to make sure we have coverage of any new functionality introduced and we didn't yet have tests for this.

**Comment by jrogov** [comment]
Hello, @sbuttgereit!

Please, feel free to take over this PR. It's embarassing that I couldn't find time to finish it, so I'll be more than happy if you do so!

--- 

One note: since it's clearly a change in the specification itself and the toml-elixir is a multipurpose library, probably supporting both versions would make sense to meet users' expectations (e.g. via passed options and/or `Application` env)? 

But that's up to @bitwalker to decide.

**Comment by sbuttgereit** [comment]
OK,  I'll take a look.  I'm going to be away next week so I'll try to either squeeze it in the next couple days or I'll be a couple weeks out.

**Comment by sbuttgereit** [comment]
Just an update.  

I finally got some time and I've pulled the PR and started adding "valid" tests in the fixtures for mixed type arrays.  The good news is that the changes in the original PR look like they're producing output that I would expect... this just a cursory look, but so far so good.  

The bad news is that I'm having trouble writing a test that actually fails.  This is just something I like to do to know that my test is robust and not passing for invalid reasons.  To induce failure in this case, I'm making the JSON file that matches the TOML file similar, but different.... like a value not matching, missing keys or elements, etc.  So far the only way I can make it fail is to not have the JSON file at all.   I think with the more complex types, there's something going wrong in `do_deep_equal` function clauses.  I'm starting to tear that apart now.

My thinking is that once I can get the mismatched test data to produce a failure, and then the correct test data to produce a success, that I'll push something up unless someone wants to see what I'm running into sooner.

**Pull request closed without merging**
